### ISSUE TITLE
手机浏览器打开不显示

### ISSUE THREAD

**Issue by zhufacai** [turkyden/lizhi#2]
安卓，小米自带浏览器和edge都不显示，通过播放界面下载按钮下载下来是一个1kb的mp3文件

**Comment by turkyden** [comment]
> 安卓，小米自带浏览器和edge都不显示，通过播放界面下载按钮下载下来是一个1kb的mp3文件

我来排查一下哈，确实没测试更多机型！如果你知道异常原因，方便截个图么？

**Comment by turkyden** [comment]
> 专辑里面的歌有点乱，比如在播放1701里的定西的时候实际播放的是演唱会版本

这个可能是我用了模糊搜索，没匹配好哈！我调整一下，感谢反馈！

**Comment by turkyden** [comment]
哈哈，确实时间紧迫，我做的比较粗糙，大家也可以 fork 一份 DIY 自己的哈！Bug 我会慢慢修复的，也方便一些不会前端的人上来听歌，感谢建议！
